-- MySQL dump 10.13  Distrib 5.7.9, for Win64 (x86_64)
--
-- Host: localhost    Database: process
-- ------------------------------------------------------
-- Server version	5.7.11-enterprise-commercial-advanced-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `projects`
--

LOCK TABLES `projects` WRITE;
/*!40000 ALTER TABLE `projects` DISABLE KEYS */;
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('2', 'sys-dt1', '2', 'DT1', '300', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-05 03:37:59', '2014-05-16 08:42:54');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('3', 'sys-dt2', '2', 'DT2', '300', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-05 03:38:08', '2013-05-01 23:18:30');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('4', 'sys-dt3', '2', 'DT3', '300', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-05 03:38:26', '2013-05-01 23:18:38');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('5', 'sys-sop', '2', 'SYS-SOP', '300', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-05 03:38:45', '2014-06-26 04:21:07');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('6', 'sys-gbu', '2', 'SYS-GBU', '300', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-05 03:39:03', '2014-06-26 04:20:16');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('7', 'sys-sdev', '2', 'SYS-SDEV', '300', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-05 03:39:58', '2014-06-26 04:20:50');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('8', 'sys-dt1-gs', '2', 'GS保守', '300', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-12 10:17:38', '2013-05-01 23:16:22');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('9', 'sys-dt1-cms', '2', '201_CMS保守/メディア案件', '1', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-12 10:17:55', '2014-05-16 08:37:39');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('10', 'sys-dt2-iphone', '2', 'iPhoneアプリ保守', '2', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-12 10:18:50', '2014-03-11 02:43:38');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('11', 'sys-dt2-android', '2', 'Androidアプリ保守', '3', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-12 10:19:08', '2014-03-11 02:43:30');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('12', 'sys-dt3-golftec', '2', 'GolfTEC', '4', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-12 10:19:38', '2013-10-23 01:33:07');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('13', 'sys-dt3-ope', '2', '401_運用保守', '5', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-12 10:21:46', '2014-03-11 02:44:41');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('14', 'sys-dt3-hotprice', '2', '事前決済', '6', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-12 10:22:35', '2014-03-11 02:44:18');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('15', 'sys-dt1-op', '2', '一人予約保守', '7', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-12 10:45:54', '2014-03-11 02:42:07');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('16', 'sys-dt1-smart', '2', 'スマートコンペ保守', '8', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-12 10:46:22', '2014-03-11 02:41:58');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('17', 'sys-dt1-sw', '2', 'SW（スマホWeb）対応', '9', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-12 10:46:57', '2014-03-11 02:40:46');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('18', 'sys-dt-seta', '2', 'DT-SETA', '10', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-17 16:10:33', '2013-05-01 23:17:49');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('19', 'sys-sop-bit-2-aws', '2', 'GolfTECサーバ移行', '11', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-04-24 05:10:39', '2014-06-26 04:23:42');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('20', 'sys-dt3-facebook', '2', 'ゴルフ幹事アプリ', '12', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-05-01 23:15:07', '2014-03-11 02:44:11');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('21', 'mbsd_ir', '2', 'Z1.MBSD Incident Report', '13', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-05-07 13:23:55', '2014-06-26 04:26:20');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('22', 'sys-dt1-dt2-score', '2', '501_スコア管理アプリ', '14', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-06-10 08:54:00', '2014-03-03 16:37:29');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('23', 'sys-dt3-manhour-pj', '2', '402_工数管理システム開発', '16', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-07-18 02:54:16', '2014-04-25 08:08:36');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('24', 'sys-dt2-tourapp', '2', '202_ツアーアプリ', '15', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-07-19 06:27:17', '2014-06-26 04:25:37');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('25', 'sys-coupon', '2', '108_クーポン開発PJ', '17', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-09-11 10:51:45', '2014-06-26 04:23:57');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('26', 'sys-dt1-wp2spb', '2', '601_WP2スマフォブラウザ対応', '18', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-10-28 06:39:43', '2014-06-26 04:25:51');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('27', 'sys-scirocco-autotest', '2', 'SciroccoCloudテスト自動化検証', '19', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2013-11-26 11:02:59', '2014-06-26 04:26:06');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('28', 'sys-dt1-search-renew', '2', '検索サーバリニューアル', '20', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-07 09:04:22', '2014-03-11 02:42:13');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('29', 'sys-rsv', '2', '10_予約Grp', '21', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:27:27', '2014-01-27 01:30:55');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('30', 'sys-cms_media', '2', '20_CMS/メディアGrp', '22', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:29:56', '2014-01-27 01:30:37');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('31', 'sys-gollftec_grp', '2', '30_ゴルフテックGrp', '23', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:32:11', '2014-01-27 01:32:11');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('32', 'sys-ope_mainte', '2', '40_運用保守Grp', '24', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:33:30', '2014-01-27 01:33:30');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('33', 'sys-rsv_grp', '2', '10_予約Grp', '25', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:34:13', '2014-01-27 01:34:13');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('34', 'sys-cms_media_grp', '2', '20_CMS/メディアGrp', '26', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:36:17', '2014-06-26 04:25:20');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('35', 'sys-rsv_grp_gs_pc', '2', '101_GS（PC)', '27', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:38:16', '2014-01-27 01:38:16');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('36', 'sys-rsv_grp_gs_sp', '2', '102_GS（スマフォ)', '28', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:38:53', '2014-01-27 01:38:53');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('37', 'sys-rsv_grp_gsclub_gsbureau', '2', '103_GSゴルフ場管理・事務局', '29', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:39:54', '2014-01-27 01:39:54');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('38', 'sys-rsv_grp_hp_oc_sc', '2', '104_HOTPRICE/一人予約/スマコン', '30', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:41:01', '2014-01-27 01:41:01');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('40', 'sys-rsv_grp_rsvapp', '2', '106_予約アプリ開発・改修', '30', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:42:17', '2014-01-27 01:42:17');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('41', 'sys-rsv_grp_seo', '2', '107_SEO対策', '31', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:42:40', '2014-01-27 01:42:40');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('43', 'sys-rsv_grp_oter', '2', '109_その他保守', '32', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:44:01', '2014-01-27 01:44:01');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('44', 'sys-rsv_grp_premium', '2', '111_プレミアム倶楽部', '33', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:46:41', '2014-01-27 01:46:41');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('45', 'sys-rsv_grp_new_community', '2', '112_新コミュニティ', '34', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:47:45', '2014-01-27 01:47:45');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('46', 'sys-rsv_grp_amazon', '2', '113_Amazonアライアンス', '35', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:48:52', '2014-01-27 01:48:52');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('49', 'sys-gollftec_grp_golttec', '2', '301_ゴルフテック', '36', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:51:51', '2014-03-27 07:49:32');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('51', 'sys-rsv_grp_search_renew', '2', '110_検索リニューアル', '37', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-01-27 01:54:58', '2014-02-12 00:40:47');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('52', 'sys-cxd_grp', '2', '50_CXDGrp', '38', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-03-03 10:14:06', '2014-03-03 10:14:06');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('53', 'sys-cxd_grp_scoreapp', '2', '502_スコア管理Web', '39', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-03-03 10:18:33', '2014-03-11 02:39:54');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('54', 'sys-sol_grp', '2', '60_SOLGrp', '40', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-03-03 10:47:04', '2014-03-03 10:48:58');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('56', 'sys-scirocco-autotest-score', '2', '701_スコアアプリ', '41', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-04-04 01:22:15', '2014-04-04 01:22:15');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('57', 'sys-scirocco-autotest-tour', '2', '702_ツアーアプリ', '42', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-04-04 01:23:05', '2014-04-04 01:23:05');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('58', 'sys-scirocco-autotest-web', '2', '703_Ｗｅｂ系の自動化テスト(Selennium)', '43', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-04-15 01:09:21', '2014-04-15 01:09:21');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('59', 'sys-rsv_grp_tax2', '2', '114_消費税対応フェーズ2', '44', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-04-25 03:40:42', '2014-04-25 03:40:42');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('60', 'sys-rsv_grp_tyokuzen', '2', '115_直前予約', '45', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-06-03 03:39:16', '2014-06-03 03:39:16');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('61', 'sys-pmo', '2', 'zz_PMO作業依頼', '46', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-06-11 04:24:55', '2014-06-11 04:26:36');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('62', 'sys-sop-eval', '2', 'Evaluation申し込みフロー改修', '47', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-06-26 03:59:01', '2014-06-26 03:59:01');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('63', 'sys-rsv_grp_pdca', '2', '105_PDCA対応', '48', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-06-30 10:11:42', '2014-06-30 10:12:33');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('64', 'seta_bse', '2', 'yy_BSEs作業管理', '49', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-07-02 02:45:37', '2014-07-02 02:45:37');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('65', 'sys-rsv_grp_cs', '2', '116_マスターズ', '50', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-07-02 12:17:42', '2015-11-13 01:46:51');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('66', 'sys-rsv_grp_gb', '2', '117_グループボード', '51', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-07-15 12:25:01', '2014-07-15 12:25:01');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('67', 'sys-rsv_grp_gs_other', '2', '999_その他', '51', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-08-26 01:49:31', '2014-08-26 01:49:31');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('68', 'sys-rsv_grp_yc', '2', '118_YardageClub画面解像度対応', '52', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-09-30 06:51:48', '2014-09-30 06:51:48');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('69', 'sys-rsv_grp_hpapp', '2', '119_HOTPRICEアプリ', '53', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-10-15 07:16:58', '2014-10-15 07:16:58');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('70', 'sys-cxd_grp_phonebookingapp_api', '2', '510_電話予約アプリAPI開発', '54', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2014-10-31 02:08:01', '2014-10-31 02:08:01');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('71', 'sys-rsv_grp_quality_control', '2', '120_予約品質管理', '55', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2015-02-02 01:38:51', '2015-02-02 01:38:51');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('72', 'common_action_plan', '2', '00_ActionPlan_PRJ', '56', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2015-03-30 07:36:01', '2015-03-30 07:36:01');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('73', 'management-strategy_grp', '2', '80_経営戦略Grp', '57', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2015-06-02 04:46:10', '2015-06-02 05:36:15');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('74', 'management-strategy_grp_wpfs', '2', '801_WPFS for Taiwan', '58', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2015-06-02 04:51:18', '2015-07-02 04:37:29');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('75', 'management-strategy_grp_photoupload_app', '2', '802_写真投稿アプリ', '59', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2015-06-02 04:57:34', '2015-06-02 05:36:49');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('76', 'sys-rsv_grp_smartcompe', '2', '121_スマコン', '60', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2015-07-22 12:41:21', '2015-07-22 12:41:21');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('77', 'management-strategy_grp_thailand', '2', '803_タイ向け予約サービス', '61', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2016-03-25 02:48:01', '2016-03-25 02:48:01');
INSERT INTO `process`.`projects` (`id`, `project_id`, `stream_id`, `name`, `brse`, `status`, `type_id`, `customer_name`, `language_id`, `process_apply`, `plant_total_effort`, `actual_effort`, `member_assign`, `description`, `resource_need_brse`, `resource_need_dev`, `resource_need_qa`, `user_id`, `created_at`, `updated_at`) VALUES ('78', 'sys-rsv_grp_rsv_flow3', '2', '122_予約フロー改修フェーズ3（変更・キャンセル）', '62', '0', '0', '', '0', '', '', '', '', '', '0', '0', '0', '0', '2016-03-30 04:03:23', '2016-03-30 04:03:23');

/*!40000 ALTER TABLE `projects` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2016-08-31 13:20:02
